bug fixed

diff --git a/etc/install b/etc/install
--- a/etc/install
+++ b/etc/install
@@ -92,13 +92,14 @@ latex_initialize() {
     if [ "$1" = "init" ]; then
         echo "Initializing latex..."
 
-    if [ -f Makefile ]; then
-        make init
-    else
-        echo "error: Makefile: not found"
-        exit 1
+        if [ -f Makefile ]; then
+            make init
+        else
+            echo "error: Makefile: not found"
+            exit 1
+        fi
+        echo "Success Initialize"
     fi
-    echo "Success Initialize"
 }
 
 # A script for the file named "install"
